export const DataArray = [
    {
        "id":1,
        "name":"HTML",
        "src":"html5.svg"
    },
    {
        "id":2,
        "name":"CSS",
        "src":"css.svg"
    },
    {
        "id":3,
        "name":"SASS",
        "src":"sass.png"
    },
    {
        "id":4,
        "name":"BootStrap",
        "src":"bootstrap.png"
    },
    {
        "id":5,
        "name":"Javascript",
        "src":"js.png"
    },
    {
        "id":6,
        "name":"React",
        "src":"react.png"
    },
    {
        "id":7,
        "name":"Redux",
        "src":"redux.png"
    },
    {
        "id":8,
        "name":"Vue",
        "src":"vue.png"
    },
    {
        "id":9,
        "name":"Node JS",
        "src":"node.svg"
    },
    {
        "id":10,
        "name":"Express",
        "src":"expressjs.svg"
    },
    {
        "id":11,
        "name":"MongoDB",
        "src":"mongodb.svg"
    },
    {
        "id":12,
        "name":"Firebase",
        "src":"firebase.png"
    },
    {
        "id":13,
        "name":"PostgreSQL",
        "src":"postql.png"
    },
    {
        "id":14,
        "name":"Heroku",
        "src":"heroku.svg"
    }
]